name: Schedule Daily Challenge

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Edge Function
        run: |
          curl -X POST \
            'https://xiwiimugmjeolprebiny.supabase.co/functions/v1/add_daily_challenge' \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd2lpbXVnbWplb2xwcmViaW55Iiwicm9sZSIsInNlcml2Y2Vfcm9sZSIsImlhdCI6MTcyNDEwNzU2MywiZXhwIjoyMDM5NjgzNTYzfQ.yoSbpwcV6S_BPqKxdhyREIwB5-ZDPh35Jxs1mo_1Uz4"
